export { default as StaffDashboard } from './StaffDashboard';
export { default as ProductManagement } from './ProductManagement';
export { default as CreateProduct } from './CreateProduct';
export { default as EditProduct } from './EditProduct';
export { default as ProductDetailManagement } from './ProductDetailManagement';
export { default as CategoryManagement } from './CategoryManagement';
export { default as StaffOrderManagement } from './StaffOrderManagement';
export { default as InventoryManagement } from './InventoryManagement';
export { default as ReviewManagement } from './ReviewManagement';
